# server port set
server:
  port: 0

# eureka client set
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    # eureka server location
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# log set
logging:
  level:
    com.coviscon.itemservice: debug

# actuator set
management:
  endpoints:
    web:
      exposure:
        include: health, beans, info, busrefresh, metrics, prometheus

image:
  save:
    path: src/main/resources/static/image
  file:
    path: file:///src/main/resources/static/image/

# path set
redirect:
  url: 'redirect:http://3.39.96.34:8000/item-service/'

prefix:
  url: 'http://3.39.96.34:8000/item-service/'
  order: 'http://3.39.96.34:8000/order-service/'
  post: 'http://3.39.96.34:8000/post-service/'
  member: 'http://3.39.96.34:8000/member-service/'