# server port set
server:
  port: 0

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    converters:
      preferred-json-mapper: gson
  application:
    name: post-service
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  # zipkin set
#  zipkin:
#    base-url: http://127.0.0.1:9411
#    enabled: true
  # sleuth set
#  sleuth:
#    sampler:
#      probability: 1.0
  # rabbitmq set
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
  # DB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/post_service
    username: root
    password: 1234
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# eureka client set
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    # eureka server location
    service-url:
      defaultZone: Http://127.0.0.1:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# log set
logging:
  level:
    com.coviscon.postservice: debug

# actuator set
management:
  endpoints:
    web:
      exposure:
        include: health, beans, info, busfresh, metrics, prometheus

image:
  save:
    path: src/main/resources/static/image/

redirect:
  url: 'redirect:http://127.0.0.1:8000/post-service/'

prefix:
  url: 'http://127.0.0.1:8000/post-service/'
